"""Add LikedProduct table

Revision ID: 505ef88cdc62
Revises: 7213fc3c05fa
Create Date: 2021-03-24 17:56:53.690408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505ef88cdc62'
down_revision = '7213fc3c05fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_products')
    # ### end Alembic commands ###
