"""Add primary image to product

Revision ID: 7b3e1ba39146
Revises: 3f83904fd620
Create Date: 2021-04-25 15:43:40.583639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3e1ba39146'
down_revision = '3f83904fd620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'primary')
    op.add_column('products', sa.Column('primary_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'primary_image')
    op.add_column('images', sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
