"""State

Revision ID: 658486c38540
Revises: 7b3e1ba39146
Create Date: 2021-05-07 22:31:47.213684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658486c38540'
down_revision = '7b3e1ba39146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
