"""Change product_icon length

Revision ID: ce859ed9d692
Revises: ef5ce3f9d206
Create Date: 2021-04-20 14:52:36.204060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce859ed9d692'
down_revision = 'ef5ce3f9d206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_icon')
    op.add_column('products', sa.Column('product_icon', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_icon')
    op.add_column('products', sa.Column('product_icon', sa.VARCHAR(
        length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
