"""New User

Revision ID: 4dfccd6a9d68
Revises: 9382ebf6a156
Create Date: 2021-02-17 16:47:57.999463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfccd6a9d68'
down_revision = '9382ebf6a156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_addr', sa.String(
        length=30), nullable=False, server_default='lorem-ipsum'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_addr')
    # ### end Alembic commands ###
